packages:
  - apps/*
  - packages/*
catalog:
  '@antfu/eslint-config': ^4.10.1
  '@commitlint/cli': ^19.8.0
  '@commitlint/config-conventional': ^19.8.0
  '@date-fns/tz': ^1.2.0
  '@dicebear/collection': ^9.2.2
  '@dicebear/core': ^9.2.2
  '@iconify-json/circle-flags': ^1.2.6
  '@iconify-json/fluent-emoji-flat': ^1.2.3
  '@iconify-json/lucide': ^1.2.31
  '@iconify-json/pixelarticons': ^1.2.2
  '@iconify-json/simple-icons': ^1.2.29
  '@neoconfetti/vue': ^2.2.1
  '@nuxt/devtools': ^2.3.0
  '@nuxt/image': ^1.9.0
  '@nuxt/ui': ^3.0.0
  '@nuxtjs/i18n': ^9.3.1
  '@paralleldrive/cuid2': ^2.2.2
  '@pinia/nuxt': ^0.10.1
  '@semantic-release/exec': ^7.0.3
  '@semantic-release/git': ^10.0.1
  '@types/bcrypt': ^5.0.2
  '@types/node': ^22.13.10
  '@types/nodemailer': ^6.4.17
  '@vitejs/plugin-vue': ^5.2.3
  '@vitest/browser': ^3.0.9
  '@vitest/coverage-v8': ^3.0.9
  '@vue-email/components': ^0.0.21
  '@vue-email/render': ^0.0.9
  '@vueuse/core': ^13.0.0
  '@vueuse/nuxt': ^13.0.0
  aws4fetch: ^1.0.20
  bcrypt: ^5.1.1
  dotenv: ^16.4.7
  dotenv-cli: ^8.0.0
  eslint: ^9.22.0
  husky: ^9.1.7
  ioredis: ^5.6.0
  libphonenumber-js: ^1.12.6
  lint-staged: ^15.5.0
  nodemailer: ^6.10.0
  nuxt: ^3.16.0
  nuxt-auth-utils: ^0.5.16
  nuxt-zod-i18n: ^1.11.5
  pinia: ^3.0.1
  playwright: ^1.51.1
  semantic-release: ^24.2.3
  semantic-release-monorepo: ^8.0.2
  typescript: ^5.8.2
  vite: ^6.2.2
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.0.9
  vitest-browser-vue: ^0.2.0
  zod: ^3.24.2
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - msw
  - vue-demi
onlyBuiltDependencies:
  - bcrypt
  - sharp
supportedArchitectures:
  cpu: [x64, arm64]
  os: [linux, darwin, win32]
